openapi: 3.0.4
info:
  title: IntegrationHub
  description: Integration Hub is an integration management service that allows integration management and guaranteed delivery of events between systems.
  version: 0.1.0
  contact:
    name: Developer
    email: andrei.solowiew122295@gmail.com

paths:
  /integrations:
    get:
      summary: List of integrations.
      description: Returns a list of configured integrations that define webhook processing and delivery rules.
      responses:
        200:
          description: Successfully retrieved the list of integrations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationList'
        400:
          description: Incorrect query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInternalServer'
    post:
      summary: Create new Integration
      description: Create new Integration.
      requestBody:
        description: Data of new Integration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntegrationCreateRequestBody'
      responses:
        201:
          description: Successfully created the integration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Integration'
        400:
          description: Incorrect query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        409:
          description: Integration with this name is already exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorConflict'

        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInternalServer'

  /integrations/{id}:
    get:
      summary: Integration by ID
      description: Returns the integration configuration by its ID.
      parameters:
        - name: id
          in: path
          description: Integration ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully retrieved the integration by his ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Integration'
        400:
          description: Incorrect query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        404:
          description: Integration with this ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInternalServer'

components:
  schemas:
    Header:
      type: object
      properties:
        name:
          type: string
          description: Name of header
          example: Authentication
        value:
          type: string
          description: Value of header
          example: Bearer 135533
      required:
        - name
        - value

    IntegrationBase:
      type: object
      properties:
        id: # ID
          type: integer
          description: ID
          readOnly: true
          example: 1
        name: # Имя
          type: string
          description: name
          example: From source.ru to target.ru
        # 1. Кто отправляет
        sourceUrl: # URL источника
          type: string
          format: uri
          description: URL where webhooks are sent from
          example: https://source.ru
        authValidation: # Валидация аутентификации
          type: object
          description: The parameters used to verify the correctness of webhooks in terms of authentication
          required:
            - authType
            - authConfig
          properties:
            authType: # Тип аутентификации
              type: string
              description: 'Type of authentication: api_key, bearer'
              example: api_key
              enum: [api_key, bearer]
            authConfig: # Конфиг для валидации аутентификации
              type: object
              description: The configuration according to which the correctness of authentication data is checked
              properties:
                source: # Откуда берем данные (заголовок или запрос)
                  type: string
                  description: Source of data. Header or query param
                  example: query
                  enum: [header, query]
                name: # Имя (заголовка или параметра запроса)
                  type: string
                  description: Name of header or query param
                  example: key
                value: # Значение
                  type: string
                  description: Value
                  example: a13f4
              required:
                - source
                - name
                - value
        # 2. Куда отправлять
        targetUrl: # URL, куда отправляем
          type: string
          format: uri
          description: The URL where the webhooks will be sent
          example: https://target.ru
        httpMethod: # HTTP-метод, которым отправляем
          type: string
          enum: [GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD]
          description: HTTP-method, which use for sending webhooks
          example: POST
        headers: # Массив заголовков, который отправляем
          type: array
          description: Array of headers, which send with webhooks
          items:
            $ref: '#/components/schemas/Header'
        # 3. Политика доставки
        maxRetryCount: # max retry count
          type: integer
          description: Defines the number of retry attempts if webhook delivery fails
          example: 4
        backoffStrategy: # Backoff-стратегия
          type: string
          description: Strategy for repeating operations in case of failure
          enum: [fixed, exponential]
          example: fixed
        deadLetterRule: # dead-letter правило
          type: string
          description: Rule for processing undelivered webhooks
          enum: [retry, discard]
          example: discard
        # 4. Состояние
        isActive: # активна / отключена
          type: boolean
          description: Active or not
          example: true
        # createdAt and updatedAt
        createdAt:
          type: string
          format: date-time
          example: '2025-03-10T12:45:00Z'
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          example: '2025-03-10T12:45:00Z'
          readOnly: true

    Integration:
      allOf:
        - $ref: '#/components/schemas/IntegrationBase'
      required:
        - id
        - name
        - targetUrl
        - httpMethod
        - maxRetryCount
        - backoffStrategy
        - deadLetterRule
        - isActive
        - sourceUrl
        - createdAt
        - updatedAt

    IntegrationList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Integration'
        total:
          type: integer
          example: 24
      required:
        - items
        - total

    IntegrationCreateRequestBody:
      description: Request body of POST /integrations
      allOf:
        - $ref: '#/components/schemas/IntegrationBase'
        - type: object
          required:
            - name
            - targetUrl
            - httpMethod
            - maxRetryCount
            - backoffStrategy
            - deadLetterRule
            - sourceUrl

    Error:
      type: object
      description: Standard error shape.
      properties:
        message:
          type: string
          description: Error message.
        error:
          type: string
          description: Type of Error.
        statusCode:
          type: number
          description: HTTP status code.
    ErrorBadRequest:
      description: Bad request
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            message:
              oneOf:
                - type: string
                  example: id must be integer
                - type: array
                  description: Array of error messages
                  items:
                    type: string
              example: ['name must be a string', 'name should not be empty']
            error:
              default: Bad request
            statusCode:
              default: 400
    ErrorNotFound:
      description: NotFound
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            message:
              example: Element with this ID not found
            error:
              default: Not Found
            statusCode:
              default: 404
    ErrorConflict:
      description: Conflict
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            message:
              example: 'Integration with this name is already exist'
            error:
              default: Conflict
            statusCode:
              default: 409
    ErrorInternalServer:
      description: Internal server error
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            message:
              example: Too many connections
            error:
              default: Internal server error
            statusCode:
              default: 500
